---

- name: Enable EPEL Repository on CentOS 7
  yum:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

- name: Install Redis client
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - redis
