---

- hosts: backend
  become: true

  pre_tasks:
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0
    - name: Ensure existence of log directory
      file:
        path: "/data/mutualaid/log"
        state: directory


  roles:
    - role: redis-cli
    - role: mysql-client
    - role: docker
