// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAuthCode = "auth_code"

// AuthCode mapped from table <auth_code>
type AuthCode struct {
	ID        uint64 `gorm:"primaryKey;autoIncrement:false" json:"id"`               // 自增id
	Phone     string `gorm:"column:phone;not null" json:"phone"`                     // 用户手机号
	Code      string `gorm:"column:code;not null" json:"code"`                       // 随机验证码
	Status    int32  `gorm:"column:status;not null;default:1" json:"status"`         // 验证状态: 0-新建，1-失效
	SendTimes int32  `gorm:"column:send_times;not null;default:0" json:"send_times"` // 发送次数
	CreatedAt int64  `gorm:"column:created_at;not null" json:"created_at"`           // 创建时间，用unix时间戳表示
	ExpiredAt int64  `gorm:"column:expired_at;not null" json:"expired_at"`           // 过期时间，用unix时间戳表示
}

// TableName AuthCode's table name
func (*AuthCode) TableName() string {
	return TableNameAuthCode
}
