// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameExamineUser = "examine_user"

// ExamineUser mapped from table <examine_user>
type ExamineUser struct {
	ID       uint64 `gorm:"primaryKey;autoIncrement:false" json:"id"` // 用户ID,自增
	NameCn   string `gorm:"column:name_cn" json:"name_cn"`            // 中文名
	UserName string `gorm:"column:user_name" json:"user_name"`        // 用户名
	Password string `gorm:"column:password" json:"password"`          // 密码加盐
}

// TableName ExamineUser's table name
func (*ExamineUser) TableName() string {
	return TableNameExamineUser
}
