// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         uint64 `gorm:"primaryKey;autoIncrement:false" json:"id"`              // 自增id
	Phone      string `gorm:"column:phone;not null" json:"phone"`                    // 用户手机号
	Name       string `gorm:"column:name;not null" json:"name"`                      // 姓名
	Icon       string `gorm:"column:icon;not null;default:''" json:"icon"`           // 头像
	Openid     string `gorm:"column:openid;not null;default:''" json:"openid"`       // 微信openid
	Unionid    string `gorm:"column:unionid;not null;default:''" json:"unionid"`     // 微信unionid
	Addr       string `gorm:"column:addr;not null" json:"addr"`                      // 联系地址
	Community  string `gorm:"column:community;not null;default:''" json:"community"` // 社区名
	Status     int32  `gorm:"column:status;not null;default:1" json:"status"`        // 用户状态: 1-新建，2-正常，3-锁定
	CreateTime int64  `gorm:"autoCreateTime" json:"create_time"`                     // 创建时间，用unix时间戳表示
	UpdateTime int64  `gorm:"autoUpdateTime" json:"update_time"`                     // 更新时间，用unix时间戳表示
	MpOpenid   string `gorm:"column:mp_openid;not null;default:''" json:"mp_openid"` // 微信公众号openid
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
